// Code generated by go-swagger; DO NOT EDIT.

package department

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "auto1.com/autonet-be/models"
)

// GetDepartmentsOKCode is the HTTP code returned for type GetDepartmentsOK
const GetDepartmentsOKCode int = 200

/*GetDepartmentsOK OK

swagger:response getDepartmentsOK
*/
type GetDepartmentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.DepartmentPage `json:"body,omitempty"`
}

// NewGetDepartmentsOK creates GetDepartmentsOK with default headers values
func NewGetDepartmentsOK() *GetDepartmentsOK {

	return &GetDepartmentsOK{}
}

// WithPayload adds the payload to the get departments o k response
func (o *GetDepartmentsOK) WithPayload(payload *models.DepartmentPage) *GetDepartmentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get departments o k response
func (o *GetDepartmentsOK) SetPayload(payload *models.DepartmentPage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDepartmentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDepartmentsUnauthorizedCode is the HTTP code returned for type GetDepartmentsUnauthorized
const GetDepartmentsUnauthorizedCode int = 401

/*GetDepartmentsUnauthorized Unauthorized

swagger:response getDepartmentsUnauthorized
*/
type GetDepartmentsUnauthorized struct {
}

// NewGetDepartmentsUnauthorized creates GetDepartmentsUnauthorized with default headers values
func NewGetDepartmentsUnauthorized() *GetDepartmentsUnauthorized {

	return &GetDepartmentsUnauthorized{}
}

// WriteResponse to the client
func (o *GetDepartmentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetDepartmentsForbiddenCode is the HTTP code returned for type GetDepartmentsForbidden
const GetDepartmentsForbiddenCode int = 403

/*GetDepartmentsForbidden Forbidden

swagger:response getDepartmentsForbidden
*/
type GetDepartmentsForbidden struct {
}

// NewGetDepartmentsForbidden creates GetDepartmentsForbidden with default headers values
func NewGetDepartmentsForbidden() *GetDepartmentsForbidden {

	return &GetDepartmentsForbidden{}
}

// WriteResponse to the client
func (o *GetDepartmentsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
