// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTeamsParams creates a new GetTeamsParams object
// no default values defined in spec.
func NewGetTeamsParams() GetTeamsParams {

	return GetTeamsParams{}
}

// GetTeamsParams contains all the bound params for the get teams operation
// typically these are obtained from a http.Request
//
// swagger:parameters getTeams
type GetTeamsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*id of the department to filter by
	  In: query
	*/
	DepartmentID *strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTeamsParams() beforehand.
func (o *GetTeamsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDepartmentID, qhkDepartmentID, _ := qs.GetOK("departmentId")
	if err := o.bindDepartmentID(qDepartmentID, qhkDepartmentID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTeamsParams) bindDepartmentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("departmentId", "query", "strfmt.UUID", raw)
	}
	o.DepartmentID = (value.(*strfmt.UUID))

	if err := o.validateDepartmentID(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetTeamsParams) validateDepartmentID(formats strfmt.Registry) error {

	if err := validate.FormatOf("departmentId", "query", "uuid", o.DepartmentID.String(), formats); err != nil {
		return err
	}

	return nil
}
