// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Contact contact
// swagger:model Contact
type Contact struct {

	// type
	Type string `json:"type,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this contact
func (m *Contact) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var contactTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["EMAIL","SLACK"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		contactTypeTypePropEnum = append(contactTypeTypePropEnum, v)
	}
}

const (

	// ContactTypeEMAIL captures enum value "EMAIL"
	ContactTypeEMAIL string = "EMAIL"

	// ContactTypeSLACK captures enum value "SLACK"
	ContactTypeSLACK string = "SLACK"
)

// prop value enum
func (m *Contact) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, contactTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Contact) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Contact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Contact) UnmarshalBinary(b []byte) error {
	var res Contact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
